### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by jy1989** [nackily/imglib#2]
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
	at java.awt.image.SinglePixelPackedSampleModel.createDataBuffer(SinglePixelPackedSampleModel.java:242)
	at sun.awt.image.IntegerInterleavedRaster.<init>(IntegerInterleavedRaster.java:73)
	at sun.awt.image.IntegerInterleavedRaster.createCompatibleWritableRaster(IntegerInterleavedRaster.java:530)
	at sun.awt.image.BufferedImageGraphicsConfig.createCompatibleImage(BufferedImageGraphicsConfig.java:102)
	at java.awt.GraphicsConfiguration.createCompatibleImage(GraphicsConfiguration.java:178)
	at cn.core.utils.BufferedImageUtils.newTransparentImage(BufferedImageUtils.java:67)
	at cn.core.utils.BufferedImageUtils.newColoredImage(BufferedImageUtils.java:86)
	at cn.core.utils.BufferedImageUtils.newBackgroundImage(BufferedImageUtils.java:46)
	at cn.pipe.ypipe.merge.GridMergeHandler.merge(GridMergeHandler.java:79)
	at cn.pipe.ypipe.AbstractMergeFilter.execute(AbstractMergeFilter.java:23)
	at cn.usage.AbstractSourceBuilder.obtainBufferedImages(AbstractSourceBuilder.java:121)
	at cn.usage.AbstractSourceBuilder.obtainBufferedImage(AbstractSourceBuilder.java:96)
	at cn.usage.AbstractSourceBuilder.toFile(AbstractSourceBuilder.java:150)
	at Demo.main(Demo.java:34)

1260张512*512的图片合并

**Comment by jy1989** [comment]
增加jvm内存暂时可解决 -Xmx8G

**Comment by nackily** [comment]
如您所说，在现阶段的确可以通过调大JVM内存来解决这个问题，在未来我也许会着手优化该项。

该问题发生的原因是最终要合成的图像太大了，根据您的描述，期望 1260 张宽高 512\*512 的图像拼接成一张图像，目标图像的像素点为 1260 \* 512 \* 512，一个像素点在占用`ARGB`为 4 个字节，那么这张图大约需要 [1260 \* 512 \* 512 \* 4 / 1000 / 1000 / 1000] 约为 1.32 GB的内存空间。

对应用程序来说，这的确是相当庞大的内存开销，或许你可以让目标图像的尺寸更小来节省内存占用，同样也可以调大-Xmx参数来让应用有足够的内存承载任务。关于这一点，我已在常见问题中补充说明，链接是：https://github.com/nackily/imglib/blob/master/docs/FAQ.md
